const exam = {
  title: 'Test',
  deadline: '2022-11-10',
  totalDuration: '25',
  perQuestionDuration: '2',
  type: 'default',
  classList: ['B.Com', 'BCA'],
  classSelect: 'BCA',
  quizType: 'Quiz2',
  questionList: [
    [
      'What is React.js?',
      ') Open-source JavaScript back-end library',
      'JavaScript front-end library to create a database',
      ' Free and open-source JavaScript front-end library',
      'None of the mentioned',
      'c',
    ],
    [
      'Which of the following acts as the input of a class-based component?',
      'Class',
      'Props',
      'Factory',
      'None of the mentioned',
      'b',
    ],
    [
      ' What is React.js? 1',
      ') Open-source JavaScript back-end library',
      'JavaScript front-end library to create a database',
      ' Free and open-source JavaScript front-end library',
      'None of the mentioned',
      'b',
    ],
    [
      'Which of the following acts as the input of a class-based component?',
      'Class',
      'Props',
      'Factory',
      'None of the mentioned',
      'b',
    ],
    [
      '  What is React.js? 2',
      ') Open-source JavaScript back-end library',
      'JavaScript front-end library to create a database',
      ' Free and open-source JavaScript front-end library',
      'None of the mentioned',
      'b',
    ],
    [
      'Which of the following acts as the input of a class-based component?',
      'Class',
      'Props',
      'Factory',
      'None of the mentioned',
      'b',
    ],
    [
      'What is React.js? 3',
      ') Open-source JavaScript back-end library',
      'JavaScript front-end library to create a database',
      ' Free and open-source JavaScript front-end library',
      'None of the mentioned',
      'b',
    ],
    [
      'Which of the following acts as the input of a class-based component?',
      'Class',
      'Props',
      'Factory',
      'None of the mentioned',
      'b',
    ],
    [
      'What is React.js? 4',
      ') Open-source JavaScript back-end library',
      'JavaScript front-end library to create a database',
      ' Free and open-source JavaScript front-end library',
      'None of the mentioned',
      'b',
    ],
    [
      'Which of the following acts as the input of a class-based component?',
      'Class',
      'Props',
      'Factory',
      'None of the mentioned',
      'b',
    ],
  ],
};
export default exam;
